# Generated by Django 3.2.9 on 2021-12-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Primitive',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('library', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('graph', models.JSONField()),
                ('rdf_file', models.FileField(null=True, upload_to='protocols/')),
            ],
        ),
        migrations.CreateModel(
            name='PrimitiveOutput',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pamled_editor.pin')),
                ('primitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='pamled_editor.primitive')),
            ],
            bases=('pamled_editor.pin',),
        ),
        migrations.CreateModel(
            name='PrimitiveInput',
            fields=[
                ('pin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pamled_editor.pin')),
                ('primitive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='pamled_editor.primitive')),
            ],
            bases=('pamled_editor.pin',),
        ),
    ]
